workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Build iOS release and generate archive
        script: |
          set -e  # Exit on error
          flutter build ipa --no-codesign --verbose
          echo "Listing contents of build/ios/archive directory:"
          ls -la build/ios/archive || echo "Directory build/ios/archive does not exist or is empty"
          if [ ! -d "build/ios/archive" ] || [ ! -f "build/ios/archive/*.xcarchive" ]; then
            echo "Error: No .xcarchive file found in build/ios/archive"
            exit 1
          fi

    artifacts:
      - build/ios/archive/*.xcarchive