workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Build iOS release and generate ipa
        script: |
          flutter build ipa --no-codesign
      - name: Debug: Show IPA path
        script: |
          echo "Checking build/ios/ipa folder..."
          ls -lh build/ios/ipa || echo "Folder not found"
          echo "Checking build/ios folder..."
          ls -lh build/ios || echo "Folder not found"

    artifacts:
      - build/ios/ipa/*.ipa
