workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_ID: "com.example.learnbound" # ← Replace with your actual App ID
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    code_signing:
      certificates:
        - certificate: ios_distribution.p12
          password: $CERTIFICATE_PASSWORD
      provisioning_profiles:
        - ios_app.mobileprovision
