workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Build iOS release and generate ipa
        script: |
          set -e  # Exit on error
          flutter build ipa --no-codesign --verbose
          echo "Listing contents of build/ios/ipa directory:"
          ls -la build/ios/ipa || echo "Directory build/ios/ipa does not exist or is empty"
          if [ ! -f "build/ios/ipa/*.ipa" ]; then
            echo "Error: No .ipa file found in build/ios/ipa"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa